In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
mk_train = pd.read_csv('.....\marketing_training.csv')
mk_test = pd.read_csv('......\marketing_test.csv')

In [3]:
pd.isnull(mk_train).any() #Finding missing data

custAge            True
profession        False
marital           False
schooling          True
default           False
housing           False
loan              False
contact           False
month             False
day_of_week        True
campaign          False
pdays             False
previous          False
poutcome          False
emp.var.rate      False
cons.price.idx    False
cons.conf.idx     False
euribor3m         False
nr.employed       False
pmonths           False
pastEmail         False
responded         False
dtype: bool

In [4]:
mk_train_age = mk_train[np.isfinite(mk_train['custAge'])]

In [5]:
mat = mk_train_age.as_matrix()

In [6]:
for i in range(len(mat)):
    if mat[i,21] == 'no':
        mat[i,21] = 0
    elif  mat[i,21] == 'yes':
        mat[i,21] = 1
    else:
        print mat[i,21]
        

In [7]:
x = mat[:,0]
x.astype(int)

array([55, 42, 55, ..., 27, 51, 38])

In [8]:
from scipy.stats.stats import pearsonr
pearsonr(x,mat[:,21])
#This is the correlation between age and target and it seems to be very low

(0.04090861423728518, 0.0021792303017186682)

In [9]:
mk_train_schooling = mk_train[mk_train.schooling.notnull()]
mk_train_schooling2 = mk_train_schooling[mk_train_schooling.schooling != 'unknown']
mk_train_schooling2.schooling.unique()

array(['university.degree', 'high.school', 'basic.4y', 'basic.9y',
       'professional.course', 'basic.6y', 'illiterate'], dtype=object)

In [10]:
mat = mk_train_schooling2.as_matrix()
for i in range(len(mat)):
    if mat[i,21] == 'no':
        mat[i,21] = 0
    elif  mat[i,21] == 'yes':
        mat[i,21] = 1
    else:
        print mat[i,21]


In [11]:
for i in range(len(mat)):
    if mat[i,3] == 'illiterate':
        mat[i,3] = 0
    elif  mat[i,3] == 'basic.4y':
        mat[i,3] = 0
    elif  mat[i,3] == 'basic.6y':
        mat[i,3] = 0
    elif  mat[i,3] == 'basic.9y':
        mat[i,3] = 0
    elif  mat[i,3] == 'high.school':
        mat[i,3] = 0
    elif  mat[i,3] == 'university.degree':
        mat[i,3] = 1
    elif  mat[i,3] == 'professional.course':
        mat[i,3] = 1
    else:
        print mat[i,21]

In [12]:
from scipy.stats.stats import pearsonr
pearsonr(mat[:,3],mat[:,21])

(0.044038377535354091, 0.0017875676497612529)

In [13]:
mk_train_day = mk_train[mk_train.day_of_week.notnull()]

In [14]:
mk_train_day.day_of_week.unique()

array(['mon', 'wed', 'tue', 'fri', 'thu'], dtype=object)

In [15]:
mat = mk_train_day.as_matrix()
for i in range(len(mat)):
    if mat[i,21] == 'no':
        mat[i,21] = 0
    elif  mat[i,21] == 'yes':
        mat[i,21] = 1
    else:
        print mat[i,21]

In [16]:
for i in range(len(mat)):
    if mat[i,9] == 'mon':
        mat[i,9] = 1
    elif  mat[i,9] == 'tue':
        mat[i,9] = 1
    elif  mat[i,9] == 'wed':
        mat[i,9] = 1
    elif  mat[i,9] == 'thu':
        mat[i,9] = 1
    elif  mat[i,9] == 'fri':
        mat[i,9] = 0
    else:
        print mat[i,9]

In [17]:
from scipy.stats.stats import pearsonr
pearsonr(mat[:,9],mat[:,21])
#although the p-value is not insignificant the correlation is low

(-0.013485006651325827, 0.2696422714366849)

In [18]:
mk_train.drop(mk_train.columns[[0, 3, 9]], axis=1, inplace=True)

In [19]:
all_cols = set(list(mk_train))
numeric_cols = set(['campaign','pdays','previous','emp.var.rate','cons.price.idx','cons.conf.idx','euribor3m','nr.employed','pmonths','pastEmail'])
col_names = list(all_cols - numeric_cols)

for col in col_names:
    categories = mk_train[col].unique()
    dic = {}
    i = 0
    for category in categories:
        dic[category] = i
        i = i+1
    print dic
    
    def transtonum(x):
        x[col] = dic[x[col]]
        return x
    
    mk_train = mk_train.apply(transtonum, axis =1)    
#Converting categorical data to numerical data

{'failure': 1, 'success': 2, 'nonexistent': 0}
{'unknown': 0, 'yes': 2, 'no': 1}
{'unknown': 2, 'yes': 1, 'no': 0}
{'management': 3, 'retired': 9, 'self-employed': 8, 'unknown': 7, 'unemployed': 5, 'housemaid': 6, 'admin.': 0, 'services': 4, 'student': 10, 'technician': 2, 'entrepreneur': 11, 'blue-collar': 1}
{'unknown': 3, 'single': 0, 'married': 1, 'divorced': 2}
{'telephone': 1, 'cellular': 0}
{'unknown': 2, 'yes': 1, 'no': 0}
{'mar': 6, 'aug': 3, 'sep': 8, 'may': 2, 'jun': 5, 'jul': 1, 'apr': 4, 'nov': 0, 'dec': 9, 'oct': 7}
{'yes': 1, 'no': 0}


In [20]:
mk = mk_train.copy() 

In [21]:
def zero_index(x):
    z = []
    for i in range(len(x)):
        if x[i,18] ==0:
            z.append(i)
    return z

def one_index(x):
    o = []
    for i in range(len(x)):
        if x[i,18] ==1:
            o.append(i)
    return o


In [22]:
mk = mk.as_matrix()
np.random.shuffle(mk)
o = one_index(mk)
z = zero_index(mk)
one_train = o[0:672]
one_test = o[672:]
zero_train = z[0:5328]
zero_test = z[5328:]

train_zero = []
train_one = []
test_one = []
test_zero = []

for i in zero_train:
    train_zero.append(mk[i])

for j in one_train:
    train_one.append(mk[j])
    
for i in zero_test:
    test_zero.append(mk[i])

for j in one_test:
    test_one.append(mk[j]) 
    


In [23]:
len(o)

840

In [24]:
train_zero = np.asarray(train_zero)
train_one = np.asarray(train_one)
test_zero = np.asarray(test_zero)
test_one = np.asarray(test_one)

In [25]:
#Oversampling to make classes more balanced
train1 = np.vstack((train_zero[0:672],train_one[0:672]))
train2 = np.vstack((train_zero[672:1344],train_one[0:672]))
train3 = np.vstack((train_zero[1344:2016],train_one[0:672]))
train4 = np.vstack((train_zero[2016:2696],train_one[0:672]))
train5 = np.vstack((train_zero[2696:3368],train_one[0:672]))
train6 = np.vstack((train_zero[3368:4040],train_one[0:672]))
train7 = np.vstack((train_zero[4040:4712],train_one[0:672]))
train8 = np.vstack((train_zero[4712:5328],train_one[0:672]))
np.random.shuffle(train1)
np.random.shuffle(train2)
np.random.shuffle(train3)
np.random.shuffle(train4)
np.random.shuffle(train5)
np.random.shuffle(train6)
np.random.shuffle(train7)
np.random.shuffle(train8)
x_train1, y_train1 = train1[:,0:18], train1[:,18]
x_train2, y_train2 = train2[:,0:18], train2[:,18]
x_train3, y_train3 = train3[:,0:18], train3[:,18]
x_train4, y_train4 = train4[:,0:18], train4[:,18]
x_train5, y_train5 = train5[:,0:18], train5[:,18]
x_train6, y_train6 = train6[:,0:18], train6[:,18]
x_train7, y_train7 = train7[:,0:18], train7[:,18]
x_train8, y_train8 = train8[:,0:18], train8[:,18]

In [26]:
#If the 1st part is commented out then it is oversampled "balanced", else if the 2nd part is commented it is unblanced
x_train = np.vstack((x_train1, x_train2, x_train3, x_train4, x_train5, x_train6, x_train7, x_train8))
y_train = np.concatenate((y_train1, y_train2, y_train3, y_train4, y_train5, y_train6, y_train7, y_train8))

"""
train = np.vstack((train_zero,train_one))
np.random.shuffle(train)
x_train, y_train = train[:,0:18], train[:,18]

"""

'\ntrain = np.vstack((train_zero,train_one))\nnp.random.shuffle(train)\nx_train, y_train = train[:,0:18], train[:,18]\n\n'

In [27]:
test = np.vstack((test_zero,test_one))
np.random.shuffle(test)
x_test, y_test = test[:,0:18], test[:,18]

Testing out Classfiers

In [30]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(n_iter=100, alpha=0.125)

clf.fit(x_train,y_train) 
ans = clf.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(y_test, ans)
print clf.score(x_test, y_test)


[[1224   22]
 [ 133   35]]
0.890381895332


In [32]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=0).fit(x_train, y_train)
ans= clf.predict(x_test) 

In [33]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(y_test, ans)
print clf.score(x_test, y_test)

[[1030  216]
 [  78   90]]
0.792079207921


In [34]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100,max_depth=10,class_weight={0:8,1:1}).fit(x_train, y_train)
ans= clf.predict(x_test) 

In [35]:
from sklearn.metrics import confusion_matrix
print confusion_matrix(y_test, ans)
print clf.score(x_test, y_test)

[[1196   50]
 [ 112   56]]
0.885431400283


In [36]:
mk_test = pd.read_csv('.....\marketing_test.csv')
mk_test.drop(mk_test.columns[[0, 1, 4, 10]], axis=1, inplace=True)
all_cols = set(list(mk_test))
numeric_cols = set(['campaign','pdays','previous','emp.var.rate','cons.price.idx','cons.conf.idx','euribor3m','nr.employed','pmonths','pastEmail'])
col_names = list(all_cols - numeric_cols)

print col_names


for col in col_names:
    categories = mk_test[col].unique()
    dic = {}
    i = 0
    for category in categories:
        dic[category] = i
        i = i+1
    print dic
    
    def transtonum(x):
        x[col] = dic[x[col]]
        return x
    
    mk_test = mk_test.apply(transtonum, axis =1)    

mk = mk_test.copy()


['poutcome', 'default', 'housing', 'profession', 'marital', 'contact', 'month', 'loan']
{'failure': 2, 'success': 1, 'nonexistent': 0}
{'unknown': 1, 'no': 0}
{'unknown': 2, 'yes': 0, 'no': 1}
{'management': 6, 'retired': 4, 'self-employed': 8, 'unknown': 10, 'unemployed': 7, 'housemaid': 11, 'admin.': 3, 'entrepreneur': 0, 'services': 5, 'student': 9, 'technician': 2, 'blue-collar': 1}
{'unknown': 2, 'single': 1, 'married': 0, 'divorced': 3}
{'telephone': 1, 'cellular': 0}
{'mar': 8, 'aug': 3, 'sep': 7, 'apr': 4, 'jun': 1, 'jul': 0, 'may': 5, 'nov': 2, 'dec': 9, 'oct': 6}
{'unknown': 2, 'yes': 1, 'no': 0}


In [37]:
x_test = mk.as_matrix()
ans= clf.predict(x_test) 

In [38]:
dic = {0:'no', 1:'yes'}
pred = []
for a in ans:
    pred.append(dic[a])


In [39]:
df = pd.DataFrame(data = ans[0:])

In [40]:
df.to_csv('....\marketing_test.csv')# saving to csv file